# Generated by Django 5.1.2 on 2024-10-21 10:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="next_date",
            field=models.DateField(
                default=datetime.datetime(2024, 10, 21, 15, 46, 58, 743651),
                verbose_name="дата следующего выполнения привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default=datetime.time(15, 46, 58, 743451),
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
